name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    container:
      image: debian:bookworm
      options: --device /dev/fuse --privileged
      env:
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt update
        apt install -y build-essential ca-certificates curl fuse gettext-base git gpg rclone reprepro
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        . "$HOME/.cargo/env"
        cargo install cargo-deb
    - name: Configure gpg
      run: |
        echo -n "$GPG_PRIVATE_KEY_BASE64" | base64 --decode | gpg --import
    - name: Configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat rclone.conf.template | envsubst > ~/.config/rclone/rclone.conf
    - name: Mount debpkgs
      run: |
        mkdir -p debpkgs
        rclone mount r2:debpkgs debpkgs --no-modtime --vfs-cache-mode full --vfs-write-back 1s --daemon
    - name: Check mount
      run: |
        ls debpkgs
    - name: Build & deploy packages
      run: |
        cd pkgr
        . "$HOME/.cargo/env"
        cargo run
    - name: Upload all files
      # rclone doesn't have a way to flush the cache and block until everything is uploaded.
      run: |
        sleep 60

